<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NOI-2870T02" ignored="0" name="test one" tests="2" failures="1" timestamp="04 Feb 2020 10:02:28 GMT" time="11.081" errors="0">
  <testcase name="myDisableTest" time="5.02" classname="otherFeatures.TimeoutTestExample">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method otherFeatures.TimeoutTestExample.myDisableTest() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method otherFeatures.TimeoutTestExample.myDisableTest() didn't finish within the time-out 5000
at java.util.concurrent.FutureTask.setException(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- myDisableTest -->
  <testcase name="myDisableTestTwo" time="6.014" classname="otherFeatures.TimeoutTestExample"/>
</testsuite> <!-- test one -->
